apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld-consumer
spec:
  replicas: 1
  template:
    metadata:
      labels:
        svc: helloworld-consumer
    spec:
      containers:
          - image: 340603795304.dkr.ecr.us-east-1.amazonaws.com/helloworld-consumer:latest
            name: helloworld-consumer
            command:
              - java
            args:
              - -jar
              - helloworld-consumer-assembly-0.1.0.jar
              - com.undercarriage.helloworld.HelloWorldConsumer
            resources:
              limits:
                cpu: 300m
                memory: 200Mi
      imagePullSecrets:
        - name: ecrkey